### ISSUE TITLE
No sound at all in Catalina 1.15.1 using the Catalina release

### ISSUE THREAD

**Issue by nendraharyo** [chris1111/Carillon-AppleALC-Version#1]
The launchDaemon plist is listed correctly and the carillon file tested successfully wit root permission. But whenever I restart or turn on my laptop it doesn't work at all. I am using AppleALC.kext

**Comment by chris1111** [comment]
This is strange ? Did you try Shutdown ?

EDIT ***
It does not work for me too I just tested it on macOS Catalina 10.15.6 I will see to find the problem

**Comment by chris1111** [comment]
[Fixed](https://github.com/chris1111/Carillon-AppleALC-Version/commit/082aa2550458e0dcdd4d1d4e130857d2f7f7a203)
